### ISSUE TITLE
Missing exe program and source code

### ISSUE THREAD

**Issue by howarduong** [v2v3v4/BigWorld-Engine-14.4.1#1]
Hello buddy, I downloaded the compressed package you uploaded to Google Cloud Drive, I probably checked it, it lacks EXE executable files, and source code, I don't know if you missed it

**Comment by v2v3v4** [comment]
In order for the exe to appear, you need to build it, the source code is there.

**Comment by v2v3v4** [comment]
source code on git and resources on google drive link

**Comment by howarduong** [comment]
Whether you can produce a detailed tutorial, I have compiled bigworldengine 2.0 before, and its official guidance teaching is very detailed. Can you also produce a detailed compilation instruction?

**Comment by howarduong** [comment]
Okay, I took a closer look, it doesn't seem to contain the client and editing tool source code, it should be created under the CentOS system of Linux. Can you share the complete source code and tutorial guide that includes the client and client assembly?

**Comment by v2v3v4** [comment]
here is the source code for both the server and the client with tools

**Comment by v2v3v4** [comment]
the server is going under the linux, yes it is

**Comment by v2v3v4** [comment]
client and toolkit are assembled under windows

**Comment by howarduong** [comment]
I was very interested in this engine to be able to make a guided tutorial. There were a lot of mistakes when CMAKE processing it, and I couldn't advance to the next step, thank you in advance

**Comment by howarduong** [comment]
Can you make a guided tutorial, I'm very interested in this engine. There were a lot of mistakes when CMAKE processing it, and I couldn't advance to the next step, thank you in advance

**Comment by v2v3v4** [comment]
what did you try to collect through cmake?

**Comment by howarduong** [comment]
I want the server and client and client tools that generate it to be built into executable state, preferably to be in a working state with the full source version of bw2.0.

**Comment by howarduong** [comment]
I tried to extract some models of World of Warcraft, import bigworldengine, to make a mod.
I am currently using windows11, vs2022 version.

**Comment by howarduong** [comment]
Well, it's that I didn't read the error message carefully, didn't install python and 141xp, I have cmake the code, entered VS2022, and am specifying DX9c, hoping to advance to the next step.

**Comment by v2v3v4** [comment]
I'm not going to tell you the obvious.
