### ISSUE TITLE
Direct 3D 9c

### ISSUE THREAD

**Issue by howarduong** [v2v3v4/BigWorld-Engine-14.4.1#2]
Hello Alex, a new question, 2014 bigworldengine, or is it using Direct 3D 9c? Didn't upgrade to 10 or 11? Thank you buddy

**Comment by v2v3v4** [comment]
almost any not the newest, for example Microsoft DirectX SDK (June 2010)

**Comment by howarduong** [comment]
Okay, thank you, Alex
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月3日 17:19
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [v2v3v4/BigWorld-Engine-14.4.1] Direct 3D 9c (Issue #2)


almost any not the newest, for example Microsoft DirectX SDK (June 2010)

―
